from enum import Enum

class SeverityLevel(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"

class AlertType(str, Enum):
    GEOFENCE_INTRUSION = "GEOFENCE INTRUSION"
    TRIPWIRE_BREACH = "TRIPWIRE BREACH"
    TACTICAL_THREAT = "TACTICAL THREAT"
    UNREGISTERED_PERSON = "UNAUTHORIZED PERSON"
    UNREGISTERED_VEHICLE = "UNREGISTERED VEHICLE"
    BEHAVIORAL_THREAT = "BEHAVIORAL THREAT ALERT"
    VEHICLE_CROSSING = "VEHICLE CROSSING"

class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    COMMANDER = "COMMANDER"
    OPERATOR = "OPERATOR"
    AUDITOR = "AUDITOR"

class CameraStatus(str, Enum):
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    STANDBY = "STANDBY"
    RECONNECTING = "RECONNECTING"

class CameraSourceType(str, Enum):
    RTSP = "RTSP"
    ONVIF = "ONVIF"
    WEBCAM = "WEBCAM"
    FILE = "FILE"

class ZoneType(str, Enum):
    GEOFENCE = "GEOFENCE"
    TRIPWIRE = "TRIPWIRE"
    EXCLUSION = "EXCLUSION"

class EvidenceStatus(str, Enum):
    NEW = "NEW"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"
